{% set version = "0.1.1" %}

package:
  name: reindent
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/R/Reindent/Reindent-{{ version }}.tar.gz
  sha256: d61226a0d0109aef3495033b42e8a0258c6bef1c014d9f26e31c62f071352b82

build:
  number: 1000
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  entry_points:
    - reindent = reindent:main
  skip: True  # [py3k]

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - reindent
  commands:
    - echo "pass" | reindent

about:
  home: https://pypi.python.org/pypi/Reindent
  license: Public Domain
  license_family: PUBLIC-DOMAIN
  license_file: 'README.txt'
  summary: reindent script by Tim Peters
  description: |
    Reindent python cleanup script
    
    Change Python (.py) files to use 4-space indents and no hard
    tab characters.  Also trim excess spaces and tabs from ends of
    lines, and remove empty lines at the end of files.  Also
    ensure the last line ends with a newline.

extra:
  recipe-maintainers:
    - smithsp
