travis:
  secure:
    BINSTAR_TOKEN: Ix+vb3VS67iTJWhEmvp8vQHToqzG6fEEWLz4RcdtINQR7MjjrH/wuWBEG6ReShIa4lZnI335iDKqnNBqWl8hYThRiC+1jAr3X2n5gfTTXkyjAsotdu+S+aLeBSrRdfF9Vj8DJ4xofyhHtQwkjdoTI/69RA7YG52HJ4kbQ8zKb58okaLStmREr2x7xUlWGF4HraQpSh7xJ6UWtT+TSw3wf9ERwTMP6QPRxvpM25jkNSVD6jQbYhsUXLcj0fX0D+ifS3t/GGXqLFUGeaedkXvka9me7VrMvYFnK9qJSi6y7ulRXciEnWYh1hJDQRERGaEpoOsLwgpTygrC9sgVG72fLEs1PWb1s8G6OmyCjK+aleynYaMOblPp+yQsRwva3nMRod7WF0+XMzCcMD/1qwBZ8YHu78QSpxvA+VrH8FmCYE/MDu6ZVh8KindtjepWkmlLmGds1uuUM+siO62oStTy8xggXQvic2yw8C0vVhYe/SoHcRU92Xr79zFnMh+XtmyCmy6meDdGcN7uXpSyk27/KqVMhYPJRuYDnrSyahazXMvw2uC1ks0HJtkDo9YkDqlVvsg9qDMRnJ6PjvHygovsTmAtwM/sWVExii37imVWcG/Vrfhyzwth7Zc+LXgywbaMwDoR5ntGNnp3+OiHrYvMLV/IolOJzs07eIw1MWYAEFk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
