travis:
  secure:
    BINSTAR_TOKEN: pp7LAggxciNblzk2JrxSA/J4eoOFi9Kfn3LO5XbHmkf04UY0VBLC3rb92OmIwJJkET+ocP+zbCftcgFEW5N+BJkOA1zQ8eVDfvxp1+/N9K4ZjI6PCOF0x5wh3r6hKUyIPI4PayLYfKKWq0mptblkcLwaLK3orFHig3qblmJAkJ18FJoy+dla/UvYl5CHYG6O0pz9I28WeIVGO2RwEPFA8V3ycjC7Q5C7L3n/+zhS7U52aAPwtQoSB5i2N174lOn+PXaeN4DKl+316CikuHr+UT91PGMjhpCUUWYunFQSvfbqs/eDOEI20c86lt9rIh1osIOeW7uUBKtXXldO023ofwSg8a8sOWbACQak17hdhb86KgaPJD+qzpLu5iczI8cHARIa70bi6djB+TpC4sWo79rUL1s6/vRHyOHCNTBqxxHv5+e7NrgptkbE/Kl302tskRr09SpUVaGzwd6pZv7Y9Diqb455rPKAvHHMdMCviBxkLH0bRi4gOTO5zY7iUVUsygeMSw1Ho3YRii/rLg6klJFJ92M6Azh4O8JG+6ZCvIFmd68CD40oKTklc4qa27Siu5CeyUaV8bvhabQv8r/9TdKJLvuxHSEzCr+Z4/jzRqkSUuz5wBQF7UC7bXkwf9tWZxd0XhXbgsiQXac0kzCoIVbhng9Xvcboc6pZelxc5+U=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
