travis:
  secure:
    BINSTAR_TOKEN: QoAWPjHo5FflXZcdB1l/t8dQmAxxjP7yHw22WOFUkZhuL8bSIV+g2xSLYfvJjAXPHBqNbO6JSesgeJ/T7dPAHBdBejQD3QU+dSf8XY8cfslJpTKSF3cfiFYAnRPsZ9CcCdZCdItv0QgMSt6H5mR19kqCqutsm2/1GHDkQdr7b8JXvHfvrGjMPs4TRn1Qskka2WfFTvO0EkJdOv2aTgpT9e8VDojBOr/32lQkDZ+EY8Fcn+4NJijYFipcw3pItYLSjAzghxJ8j0GC026Kt94HDCiTOO/KPBPZqPHHnGgoXrreZ8AbKWZCNAKNuKudpJyJ4+pVpGxppa/nOtqp9L+WfjIWVrvyXEZPLXdlEKCB8cEs/I7IF2MAtqDRsFiudRvutVOSDn4G+Ztg4s6nBD7UelMgTwMMvF1AqJ/0gp2U6JGY46mhxPXZGDkUgta72Y8uPUMwOjIWqdhpZVzeaeZ8R8Dxyj0eFz5jO/D1nnydC7WffRtV7WEI100W7/FfcNfQnRlzpWkkJYi6dDnwg/XU8pZr/vvTMXYLah94XdcD8WbDmCpDAOGMdk6mnC52Pb9Gfc9sce6sf3sTCjipL0mC1j/p+c1r/LRHOiDfaORBVmEQOikwB07OROQCChxMZ43gGFGgjG/ym76JFWJGol1GP7Fu/JMhR/aY3AxYEtRKrAE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
